### ISSUE TITLE
Unable to create commands from C#

### ISSUE THREAD

**Issue by Krutonium** [quentincaffeino/godot-console#48] opened 2021-01-24 15:45 UTC
In C#, Console is provided by System, so I can't actually seem to find a way to add a command, from C#.

**Comment by quentincaffeino** [comment] 2021-01-24 15:57
I haven't tried it but I think it should be possible.

I suppose based on the docs registering a command would look something like this:

```csharp
Console.Call("add_command", "sayHello", this, "print_hello")
	.Call("set_description", "Prints \"Hello %name%!\"")
	.Call("add_argument", "name", Variant.Type.STRING)
	.Call("register");
```

Docs for reference:

https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_differences.html#singletons
https://docs.godotengine.org/en/stable/getting_started/scripting/cross_language_scripting.html#calling-methods

If you'll be able to set it up please get back to me I'd like to know the results)

**Comment by Krutonium** [comment] 2021-01-24 16:06
I don't think that works, because in C# `system` provides `console` and so far as I can tell, you can't override that from GD.

**Comment by quentincaffeino** [comment] 2021-01-24 16:07
Could you please share the code you are using?

**Comment by Krutonium** [comment] 2021-01-24 16:09
```
using System;
using Godot;

public class ConsoleScript : Node
{
    // Declare member variables here. Examples:
    // private int a = 2;
    // private string b = "text";

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        Console.Call("add_command", "sayHello", this, "print_hello")
            .Call("set_description", "Prints \"Hello %name%!\"")
            .Call("add_argument", "name", Variant.Type.STRING)
            .Call("register");
    }

//  // Called every frame. 'delta' is the elapsed time since the previous frame.
//  public override void _Process(float delta)
//  {
//      
//  }
}
```

**Comment by quentincaffeino** [comment] 2021-01-24 16:22
I guess a quick fix would be to go project settings and rename Console to something else.

**Comment by Krutonium** [comment] 2021-01-24 16:26
Could you point me at where I would do that?

**Comment by quentincaffeino** [comment] 2021-01-24 16:29
Yeah sure: Open Project > Project Settings > Plugins, search for quentincaffeino-console

**Comment by quentincaffeino** [comment] 2021-01-24 16:35
Sorry, instead of Plugins open Autoload

**Comment by Krutonium** [comment] 2021-01-24 17:01
Changing the name seems to not work, specifically it gives me this:

![this](https://user-images.githubusercontent.com/3945538/105637494-d6842d00-5e3b-11eb-94a8-21182f31ce9a.PNG)

**Comment by quentincaffeino** [comment] 2021-01-24 17:04
Oh yeah, I'm in progress of fixing that. You could go and find&replace all occurrences of `Console.` in `res://addons/quentincaffeino-console`. Sorry for inconvenience, the project is still in active development and there are plenty of space to improve.

**Comment by Krutonium** [comment] 2021-01-24 17:06
No worries, and I totally get it ^>^

For sure, C# is still fairly new to Godot, so compatibility I've found to be hit or miss; Thank you for taking the time to help me out 👍

**Comment by quentincaffeino** [comment] 2021-01-24 17:10
That's not really a problem with C# but with how badly I wrote this project since I don't have much time to spend on it)

**Comment by Krutonium** [comment] 2021-01-24 17:18
I did a full search and replace with `find . -type f | xargs sed -i 's/Console\./InGameConsole\./g'` which worked (after I fixed references to some files haha), but I still can't figure out how to use it in C#, InGameConsole doesn't seem to exist 🤔 .

**Comment by quentincaffeino** [comment] 2021-01-24 17:20
And you have it renamed in project autoload settings? That's odd, could you please share your project.godot or whole project?)

**Comment by Krutonium** [comment] 2021-01-24 17:22
[project.zip](https://github.com/quentincaffeino/godot-console/files/5862773/project.zip)

**Comment by Krutonium** [comment] 2021-01-24 17:38
https://docs.godotengine.org/en/stable/getting_started/scripting/cross_language_scripting.html

This seems to suggest that I would need your console to be a node which doesn't seem to be how your project operates at this point :/

**Comment by quentincaffeino** [comment] 2021-01-24 18:24
On line 24 in your project godot I see you also renamed the actual file you load, this file doesn't exist actually so I suppose you also renamed actual file?
```
InGameConsole="*res://addons/quentincaffeino-console/src/InGameConsole.tscn"
```

**Comment by quentincaffeino** [comment] 2021-01-24 18:27
> This seems to suggest that I would need your console to be a node which doesn't seem to be how your project operates at this point :/

What do you mean to be a node? When console is autoloaded it is added to the root of the scene tree so in gdscript you could retrieve it by doing something like `get_node('/root/Console')`, for C# there is similar method `GetNode("/root/InGameConsole")`.

**Comment by quentincaffeino** [comment] 2021-01-24 19:00
Ok I thought that best way to test this is to try myself, I got almost everything working with no changes to the addon code. Only thing that doesn't work for me is `Call`, but if I do `c is Object` it returns True, and Call is defined on Object. So I would suggest the problem is with C# support since docs clearly states that Call is defined on object:

https://docs.godotengine.org/en/stable/getting_started/scripting/cross_language_scripting.html#calling-gdscript-methods-from-c

My code:

```csharp
using Godot;
using System;

public class new_script : Node
{
	// Declare member variables here. Examples:
	// private int a = 2;
	// private string b = "text";

	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		var c = GetNode("/root/Console");
		GD.Print(c);
		GD.Print(c is Godot.Object);
		
//		c.Call("add_command", "sayhello", this, "printhello")
//			.call("set_description", "prints \"hello %name%!\"")
//			.call("add_argument", "name", Variant.Type.String)
//			.call("register");
	}
	
	public void PrintHello(String name) {
		GD.Print("Hello " + name + "!");
	}

//  // Called every frame. 'delta' is the elapsed time since the previous frame.
//  public override void _Process(float delta)
//  {
//      
//  }
}
```

**Comment by Krutonium** [comment] 2021-01-24 19:13
Well shit, Thanks!

**Comment by quentincaffeino** [comment] 2021-01-24 20:12
No problem)
Going to leave this issue open for now as this needs to be fixed.
Best

**Comment by quentincaffeino** [comment] 2021-01-28 12:32
Thanks to folks in discord and telegram I was able to solve this pretty quickly.

C# is fine, it just required a little time to play around to get along with how it works. This is a working version:

```cs
using Godot;
using System;

public class new_script : Node
{
	public override void _Ready()
	{
		(((GetNode("/root/Console").Call("add_command", "sayhello", this, "PrintHello") as Godot.Object)
			.Call("set_description", "prints \"hello %name%!\"") as Godot.Object)
			.Call("add_argument", "name", Variant.Type.String) as Godot.Object)
			.Call("register");
	}
	
	public String PrintHello(String name = null) {
		GD.Print("Hello " + name + "!");
		return "test";
	}
}
```

One thing to take a note of: Even tho name is provided by default here, it would be still a required argument for command (right: `sayhello hello`, wrong: `sayhello` would throw no such method exception because of signature mismatch).

Also the code style is very bad because call returns generic `object` since Call could return any value.
I am planning to write some kind of C# wrapper to hide all that. Ideally it would look something like this:

```cs
...

	public override void _Ready()
	{
		QSConsole.Default()
			.AddCommand("sayhello", this, "PrintHello")
			.SetDescription("prints \"hello %name%!\"")
			.AddArgument("name", Variant.Type.String)
			.Register();
	}
	
...
```

I'm closing as I consider this solved. If you'd have any problems you can reopen this or open new issue.

Best.

**Closed by quentincaffeino** 2021-01-28 12:32 UTC
Labels: bug, good first issue, help wanted
