### ISSUE TITLE
Add Instancing functionality (e.g. console within a scene)

### ISSUE THREAD

**Issue by jacksontriffon** [quentincaffeino/godot-console#83] opened 2022-01-16 01:33 UTC
## A console within a computer in our games!

It would be fantastic to implement this console into a screen within our games. For my use case, I'm building a text editor where the player writes code and submits it through this console, so instead of linking the console to the viewport of the player it would be fantastic if we can instance the console into a separate control node and format the console's UI from the individual scene.

Any help on this topic would be highly appreciated, I'll be working on this feature so feel free to reach out.

**Comment by quentincaffeino** [comment] 2022-01-17 14:40
You can already do this to some extent. This was already discussed in https://github.com/quentincaffeino/godot-console/issues/35#issuecomment-723187447

This is definitely something I want to improve in the future, right now I'm very short on time.

If current implementation is insufficient for your use case you can try implementing things that are you missing and maybe even pr those changes. I also would suggest checking out https://github.com/lihop/godot-xterm.
I haven't tested it myself but looks really cool.

I'm going to close this issue as I believe this is a duplicate of already mentioned https://github.com/quentincaffeino/godot-console/issues/35

If you'd have other questions on this matter please ask them there. For anything else feel free to open new issue or text me on discord quentincaffeino#9674

**Closed as completed** 2022-01-17 14:41 UTC
